apiVersion: apps/v1
kind: Deployment
metadata:
  name: university-portal
  labels:
    app: university-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: university-portal
  template:
    metadata:
      labels:
        app: university-portal
    spec:
      containers:
        - name: university-portal
          image: sachintp/university-portal:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: university-portal
spec:
  selector:
    app: university-portal
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
