apiVersion: apps/v1
kind: Deployment
metadata:
  name: employer-portal
  labels:
    app: employer-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employer-portal
  template:
    metadata:
      labels:
        app: employer-portal
    spec:
      containers:
        - name: employer-portal
          image: sachintp/employer-portal:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: employer-portal
spec:
  selector:
    app: employer-portal
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
