apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-portal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/spotananthu/StudentCertificateManagement
    targetRevision: argocd
    path: frontend/student-portal/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
