apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/spotananthu/StudentCertificateManagement
    targetRevision: argocd
    path: backend/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
