apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: verification-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/spotananthu/StudentCertificateManagement
    targetRevision: argocd
    path: backend/verification-service/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
